version: "3"

services:
  database:
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      PGDATA: ${PGDATA}
      KC_DB_SCHEMA: ${KC_DB_SCHEMA}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - db_net
    volumes:
      - caudex-db-volume:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  authentication:
    build: ../authentication
    depends_on:
      - database
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: database
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_SCHEMA: ${KC_DB_SCHEMA}
      KC_DB_URL_PORT: ${DATABASE_PORT}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED}
      KC_METRICS_ENABLED: ${KC_METRICS_ENABLED}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    entrypoint: "/opt/keycloak/bin/kc.sh"
    command: ${KEYCLOAK_START_COMMAND}
    networks:
      - db_net
      - mailcatcher_net
    restart: unless-stopped
    volumes:
      - ../authentication/realms:/opt/keycloak/data/import
    ports:
      - "8080:8080"

  redis:
    image: redis:7.0.4
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_TTL: ${REDIS_TTL}
      REDIS_LOGLEVEL: ${REDIS_LOGLEVEL}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --save 20 1 --loglevel "$REDIS_LOGLEVEL" --requirepass "$REDIS_PASSWORD"
    restart: unless-stopped
    volumes:
      - caudex-cache-volume:/data
    ports:
      - "6379:6379"

  broker:
    image: rabbitmq:3.11.2-management
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_MAIL_QUEUE: ${RABBITMQ_MAIL_QUEUE}
      RABBITMQ_SECRET: ${RABBITMQ_SECRET}
    volumes:
      - caudex-mq-volume:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - mailcatcher_net

networks:
  db_net:
    driver: bridge
  mailcatcher_net:
    driver: bridge

volumes:
  caudex-db-volume:
  caudex-cache-volume:
  caudex-mq-volume:
